server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/assafdb
spring.datasource.username=postgres
spring.datasource.password=admin

security.jwt.secret-key=${JWT_SECRET_KEY:change_me_local_jwt_secret_at_least_32_chars}
