server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/assafdb
spring.datasource.username=postgres
spring.datasource.password=admin

security.jwt.secret-key=5968HLK766556581MLR812357538782PJ536Z8B8472B4B6250645367669874KH
